# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatBot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chatBotWindow(object):
    def setupUi(self, chatBotWindow):
        chatBotWindow.setObjectName("chatBotWindow")
        chatBotWindow.resize(720, 520)
        font = QtGui.QFont()
        font.setPointSize(12)
        chatBotWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(chatBotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.ageLabel.setObjectName("ageLabel")
        self.emotionLabel = QtWidgets.QLabel(self.centralwidget)
        self.emotionLabel.setGeometry(QtCore.QRect(50, 70, 131, 31))
        self.emotionLabel.setObjectName("emotionLabel")
        self.ageValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageValueLabel.setGeometry(QtCore.QRect(200, 40, 81, 16))
        self.ageValueLabel.setObjectName("ageValueLabel")
        self.emotionValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.emotionValueLabel.setGeometry(QtCore.QRect(200, 80, 101, 16))
        self.emotionValueLabel.setObjectName("emotionValueLabel")
        self.likeButton = QtWidgets.QPushButton(self.centralwidget)
        self.likeButton.setGeometry(QtCore.QRect(230, 380, 71, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/like.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.likeButton.setIcon(icon)
        self.likeButton.setIconSize(QtCore.QSize(48, 48))
        self.likeButton.setObjectName("likeButton")
        self.dislikeButton = QtWidgets.QPushButton(self.centralwidget)
        self.dislikeButton.setGeometry(QtCore.QRect(400, 380, 71, 61))
        self.dislikeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/dislike.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dislikeButton.setIcon(icon1)
        self.dislikeButton.setIconSize(QtCore.QSize(48, 48))
        self.dislikeButton.setObjectName("dislikeButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 150, 621, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.photoLabel = QtWidgets.QLabel(self.centralwidget)
        self.photoLabel.setGeometry(QtCore.QRect(520, 10, 151, 131))
        self.photoLabel.setText("")
        self.photoLabel.setScaledContents(True)
        self.photoLabel.setObjectName("photoLabel")
        chatBotWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chatBotWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        chatBotWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chatBotWindow)
        self.statusbar.setObjectName("statusbar")
        chatBotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(chatBotWindow)
        QtCore.QMetaObject.connectSlotsByName(chatBotWindow)

    def retranslateUi(self, chatBotWindow):
        _translate = QtCore.QCoreApplication.translate
        chatBotWindow.setWindowTitle(_translate("chatBotWindow", "MainWindow"))
        self.ageLabel.setText(_translate("chatBotWindow", "Yaş"))
        self.emotionLabel.setText(_translate("chatBotWindow", "Duygu Durumu"))
        self.ageValueLabel.setText(_translate("chatBotWindow", "TextLabel"))
        self.emotionValueLabel.setText(_translate("chatBotWindow", "TextLabel"))
